### ISSUE TITLE
Add Steam OS logo

### ISSUE THREAD

**Issue by MartinLeGrand** [soxaholix-pointer/place_tux#43]
Add a Steam OS logo to the other distros in the tux square
![pixil-frame-0(1)](https://user-images.githubusercontent.com/57072480/161320824-1b7d33bb-a69a-4b6d-bd3e-df09c0878fa2.png)

**Comment by IkBenAndersOK** [comment]
![pixil-frame-0](https://user-images.githubusercontent.com/57072480/161320571-1d298332-bc9e-4308-ba67-e1d3c3c4ce1a.png)

**Comment by Jacksaur** [comment]
This isn't the SteamOS logo, it's the Deck. SteamOS uses a standard purple Steam logo.

But regardless, most people would just think of regular Steam with the Steam logo, so I think using a Deck logo is still the better choice. To properly communicate what it represents.

**Comment by yamhab** [comment]
It has been added.
