### ISSUE TITLE
Arch logo is monochrome, but the template has 2 colours in it

### ISSUE THREAD

**Issue by Silejonu** [soxaholix-pointer/place_tux#47]

**Comment by yamhab** [comment]
![image](https://user-images.githubusercontent.com/50467323/161365997-c47f016b-7736-46ab-ad96-0a7c43b0b5bc.png)
It's the "shine".

**Comment by Silejonu** [comment]
I understand what it is supposed to represent, this was not my point. The logo you linked is a fan rendition of the Arch logo, not the actual Arch logo. There is no shine on the Arch logo:
![](https://archlinux.org/static/logos/archlinux-logo-dark-1200dpi.b42bd35d5916.png)

[Source.](https://archlinux.org/art/)
